' Gambas module file

'/ * *
'*
'* @ package mVarglobales.module
'* @ copyright 2009 2010 Luis Jorge Martin Aznar
'* @ version 1.0
'* @ review 1 
'* @ author Luis Jorge Martin Aznar 
'* @ e-mail ljma@telefonica.net
'* creacion = 01/06/2010
'* modificacion = 01/06/2010
'*
'* This file IS part OF TPV-ERP ©.
'*
'* This program IS free software: you can redistribute it AND / OR modify
'* it under the terms OF the GNU General PUBLIC License AS published by
'* the Free Software Foundation, either version 3 OF the License.
'*
'* This program IS distributed IN the hope that it will be useful,
'* but WITHOUT ANY WARRANTY; without even the implied warranty OF
'* MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.See the
'* GNU General PUBLIC License FOR more details.
'*
'* You should have received a COPY OF the GNU General PUBLIC License
'* along WITH this program.IfNOT, see < http: / / www.gnu.org / licenses / > .  
'* /

'mVarglobales de configuración globales de las base de datos

Public info_system As New String[]
  'System.User.Name
  'System.Host
  'Now

Public sPathTpv As String = Application.Path
Public sPathTpvIni As String = Application.path & "/.conf"
Public sPathTpvLog As String = Application.path & "/logs"


Public sBaseMadre As String
Public sPrefijo As String
Public sPrefijoTerminal As String
Public sBd_hecha As String
Public sNterminal As String
Public sIdUsuario As String
Public sUsername As String
Public sRol As String
Public sIdEmpresa As String
Public sCodEmpresa As String
Public bEdicion As Boolean = False 'reutilizable
Public iNobjeto As New Integer[] 'reutilizable

Public info_teclado As New String[]
Public info_filtro As New String[]
Public info_creamesa As New String[] '0 número mesa 1 comensales
Public pantalla_padre As Form
